
name: Update README

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update Timestamp (Forcing README Update)
        run: |
          date > timestamp.txt

      - name: Commit and Push
        run: |
          git config --global user.name 'Banti Patel'
          git config --global user.email 'patelbanti993@gmail.com'
          git add .
          git commit -m "🔄 Updated README with latest stats" || echo "No changes to commit"
          git push
